### ISSUE TITLE
First impressions

### ISSUE THREAD

**Issue by mahmoud** [wildsparx/rhythatom#1]
First of all Asher, this is beautiful! I saw the comment about Nashville notation and I didn't know what to expect, but as soon as I fired it up, sweet sweet music to my ears! (literally)

Spent at least 30 minutes playing around with it and I figured the least I can do is give a bit of feedback/feature requests:

1. You should link to your hosted version! Right now you just link to wildsparx.com, but link to http://wildsparx.com/rhythatom!
2. In some browsers the play button doesn't show up. Worked fine on my Firefox and Chrome, but he says on his Chrome: "The canvas is too tall for some reason. It's a square, and pushes the play button down unless you adjust the size or remove it."
3. It would be so sweet to be able to save out any sort of format. Whether it's audio or MIDI or even just a text file that restores the state, it would be great to have. I get not wanting to define a format if it's still changing a lot though. Maybe it can even be a string encoded into the URL anchor?
4. It would be nice to have a pause button. I end up having to turn the BPM way up to get it to come back around quick enough :)

Anyways, honestly can't heap enough praise on this. Anytime I run across some discussion of a specific chord progression, now I know to drop in to Rhythatom and listen to that progression, stripped down and synthed up!

**Comment by wildsparx** [comment]
Good points, Mahmoud, thanks. I think I fixed the canvas-too-tall issue, but there are still UI bugs lurking. I'll incorporate your other suggestions.

**Comment by wildsparx** [comment]
Great feedback. Fixed 1, 3 and 4. Still not sure how to reproduce #2.

http://wildsparx.com/rhythatom/#ayN0KkgMIEZSAgAAEAA==

**Comment by mahmoud** [comment]
Excellent! Love the new URL scheme :)
